name: deploy-marketing

on:
  push:
    branches:
      - master
    paths:
      - 'packages/marketing/**'

defaults:
  run:
    working-directory: packages/marketing

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Install dependencies and build
      - name: Install Dependencies
        run: npm install

      - name: Build the Project
        run: npm run build

      # Debug: Check if secrets are set
      - name: Debug Secrets Presence
        run: |
          if [ -z "${{ secrets.AWS_S3_BUCKET_NAME }}" ]; then
            echo "AWS_S3_BUCKET_NAME is empty or not set"
          else
            echo "AWS_S3_BUCKET_NAME is set"
          fi
          if [ -z "${{ secrets.AWS_ACCESS_KEY_ID }}" ]; then
            echo "AWS_ACCESS_KEY_ID is empty or not set"
          else
            echo "AWS_ACCESS_KEY_ID is set"
          fi
          if [ -z "${{ secrets.AWS_SECRET_ACCESS_KEY }}" ]; then
            echo "AWS_SECRET_ACCESS_KEY is empty or not set"
          else
            echo "AWS_SECRET_ACCESS_KEY is set"
          fi

      # Sync to S3
      - name: Deploy to S3
        run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/marketing/latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "eu-north-1"

        # Invalidate CloudFront cache
      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/marketing/latest/remoteEntry.js"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "eu-north-1"
